name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable with PyInstaller
        run: pyinstaller --onefile main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: executable
          path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        id: download-artifact
        uses: actions/download-artifact@v4
        with:
          name: executable

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: executable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
